libtevent: Add back the dependency on libcap
The dependency on libcap was removed by:
418d59459148621d593054dc397335d24165a655
"libtevent: rework dependencies for deterministic build"

but in fact there was not a patch to properly avoid
dependency on libcap then we got error:
|In file included from ../lib/replace/test/testsuite.c:34:0:
|../lib/replace/system/capability.h:40:28: fatal error: sys/capability.h: No such file or directory
|compilation terminated.

so add the dependency back.

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>